#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'maximumPower' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def get_pow(k):
    count = 0
    m = 0
    for i in range(len(k)):
        if k[i] == '0':
            count = count + 1
        else:
            if m < count:
                m = count
            count = 0
    if m < count:
        m = count
    return m

def maximumPower(s):
    w = 0
    flag = 0
    n = len(s)
    k = list(s)
    for i in range(n):
        t = k.pop()
        k.insert(0, t)
        if k[0] == '1':
            w = get_pow(k)
            break
        flag = flag + 1
    if flag == n:
        return -1
    else:
        return w

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    s = input()
    result = maximumPower(s)
    fptr.write(str(result) + '\n')
    fptr.close()
