#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'maximumStones' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

n=int(input())
lst = list(map(int,input().split()))[:n]
odd_sum = 0
even_sum =0
for i in range(0,len(lst)):
    if i%2==0:
        even_sum = even_sum + lst[i]
    else:
        odd_sum = odd_sum +lst[i]
while(even_sum != odd_sum):
    if(even_sum>odd_sum):
        even_sum = even_sum - 1
    elif(even_sum<odd_sum):
        odd_sum = odd_sum - 1
print(even_sum*2)
